# Generated by Django 3.0.4 on 2020-08-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200802_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('Published', 'Published')], default='draft', max_length=10),
        ),
    ]
